# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.3.3
_src_path: https://github.com/epics-containers/ioc-template
description: 'This project attempts to integrate ZeroMQ with areaDetector framework,
    in two folds:


    - a driver pulls data from a ZeroMQ server and generates NDArray.

    - a plugin publishes NDArray as ZeroMQ server.'
git_platform: github.com
github_org: epics-containers
name: ioc-adzmq
repo_uri: git@github.com:epics-containers/ioc-adzmq.git
rtems: false
